### ISSUE TITLE
Think more of this should be moved to OI.

### ISSUE THREAD

**Issue by rpbritton** [NorthernForce/DeepSpace#4]
https://github.com/NorthernForce/DeepSpace/blob/43b4b94b52a7c64e2af3a55386d71dac16c12e2f/DeepSpace/src/main/cpp/commands/DriveWithJoystick.cpp#L21-L24

Perhaps something like `getAxis(int controller, int axis)` so DriveWithJoystick doesn't even have to see the joystick object.

**Comment by jcrosbyME** [comment]
I would be in favor of keeping them separate.

**Comment by rpbritton** [comment]
6031bf9ce6c1f4b611add788c4b627c5ce51c7c4
