### ISSUE TITLE
Need to find the can bus port for the cargo manipulator motor.

### ISSUE THREAD

**Issue by rpbritton** [NorthernForce/DeepSpace#8]
https://github.com/NorthernForce/DeepSpace/blob/52da41969a78b88e2290a6d572db6bc3b63c4169/DeepSpace/src/main/include/RobotMap.h#L47-L48

**Comment by jcrosbyME** [comment]
The list of Talons can be obtained in the Lifeboat (or is it Lifeguard) app from CTR.

-Jay Crosby
(Sent from my iPhone)

________________________________

**Comment by rpbritton** [comment]
I am just waiting for the electrical team to wire up the cargo intake and do some labeling. I could probably talk to them, too.

**Comment by jcrosbyME** [comment]
Talking is good!

-Jay Crosby
(Sent from my iPhone)

________________________________

**Comment by rpbritton** [comment]
Found it
